feat: added multiplier to type limits
ladybug-tools/honeybee-doe2 pull request #118
Opened 2024-06-20 16:13 UTC by TfedUD

This PR adds an additional type limit to the ```def schedule_type_limit_to_inp```

2024-06-20 18:54 UTC, chriswmackey requested changes
Hey @TfedUD ,

I support making this change but it's not implemented correctly. Honeybee-energy ScheduleTypeLimits are objects that have their own properties. They are different from ScheduleTypeLimits in DOE-2 where it's really just a bit of text that denotes what the type is.

So, instead of:
```
elif type_limit  == 'Multiplier'
```
it should be:
```
elif type_limit.display_name  == 'Multiplier'
```
See here in the honeybee-energy docs for more guidance:
https://www.ladybug.tools/honeybee-energy/docs/honeybee_energy.schedule.typelimit.html

2024-06-21 14:24 UTC, TfedUD commented
Hi @chriswmackey I didn't think type_limit had MULTIPLIER as an option.
[see typelimit.py here](https://github.com/ladybug-tools/honeybee-energy/blob/d6783d094fc558ce494a75c3fdb1ea908bf9dcc3/honeybee_energy/schedule/typelimit.py#L38) 
Also multiplier doesn't work with type_limit component
![image](https://github.com/ladybug-tools/honeybee-doe2/assets/63176386/aacc6b01-f20b-4629-bf80-2015eb93748b)

Would the ```class ScheduleTypeLimit(object)``` in typelimit.py also need modification to allow for MULTIPLIER to work?
Currently im using the ```schedule_day_to_inp``` having modified the code on my install to match the PR, but I can just as easily have the component take a ```HB Type Limit``` instead of a text string
![image](https://github.com/ladybug-tools/honeybee-doe2/assets/63176386/abddb89b-f9d9-4e39-8b36-db931e793fba)

Should the changes be your aforementioned, as well as adding multiplier to ```ScheduleTypeLimit```?

2024-06-25 14:11 UTC, chriswmackey commented
Hey @TfedUD ,

EnergyPlus does not have a `unit_type` for multiplier since multipliers are not really something that you schedule in E+, though you can kinda do this with the EMS. If you wanted to construct a type limit for something like a multiplier in E+, the type limit would probably have `discrete_` set to True, and the `unit_type` would probably be something like `Dimensionless`, `Control` or `Mode`. But that's why I was thinking that maybe we should not rely on the `unit_type` to tell us whether the type should be translated to eQuest as `Multiplier`. Maybe we should just see if the user chose the name `Multiplier` when they created the type and, if so, we translate it to the eQuest Multiplier type:

![image](https://github.com/ladybug-tools/honeybee-doe2/assets/5567574/88d953a6-3840-47aa-aa79-68e80a942fd6)

2024-07-08 13:34 UTC, TfedUD commented
Sorry about how late this edit was.

2024-07-26 14:43 UTC, chriswmackey approved these changes
LGTM!

2024-07-26 15:23 UTC, merged